name: Test ACR Login

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: List Repos
        run: az acr repository list --name ${{ secrets.ACR_NAME }} --output table
